# Default values for adm-agent-onboarding.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageRegistry: quay.io
imageRepository: citrix/adm-agent-onboarding
imageTag: 1.1.0
image: "{{ .Values.imageRegistry }}/{{ .Values.imageRepository }}:{{ .Values.imageTag }}"
pullPolicy: IfNotPresent
token:
cloudUrl: https://adm.cloud.com
apiURL:
clusterName:

admAgent:
  name: admagent
  imageRegistry: quay.io
  imageRepository: citrix/adm-agent
  imageTag: latest
  image: "{{ .Values.admAgent.imageRegistry }}/{{ .Values.admAgent.imageRepository }}:{{ .Values.admAgent.imageTag }}"
  helperImageRegistry: quay.io
  helperImageRepository: citrix/adm-agent-helper
  helperImageTag: 1.0.0
  helperImage: "{{ .Values.admAgent.helperImageRegistry }}/{{ .Values.admAgent.helperImageRepository }}:{{ .Values.admAgent.helperImageTag }}"
  loginSecret:

adc:
  IP:
  mgmtHTTPPort: 80
  mgmtHTTPSPort: 443
  loginSecret: nslogin

