# Default values for cpx-license-aggregator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

licenseAggregator:
  imageRegistry: quay.io
  imageRepository: citrix/cpx-license-aggregator
  imageTag: 1.0.0
  image: "{{ .Values.licenseAggregator.imageRegistry }}/{{ .Values.licenseAggregator.imageRepository }}:{{ .Values.licenseAggregator.imageTag }}"
  pullPolicy: IfNotPresent
  service:
    type: NodePort
    nodePort:
  username:
  securityContext: {}
  resources: {}
  loglevel: INFO
  jsonlog: FALSE

nslped:
  imageRegistry: quay.io
  imageRepository: citrix/nslped
  imageTag: 1.0.0
  image: "{{ .Values.nslped.imageRegistry }}/{{ .Values.nslped.imageRepository }}:{{ .Values.nslped.imageTag }}"
  pullPolicy: IfNotPresent
  securityContext: {}
  resources: {}

redis:
  image: redis:7.0.4
  pullPolicy: IfNotPresent
  secretName:
  securityContext: {}
  resources: {}

sidecarCertsGenerator:
  imageRegistry: quay.io
  imageRepository: citrix/cpx-sidecar-injector-certgen
  imageTag: 1.2.0
  image: "{{ .Values.sidecarCertsGenerator.imageRegistry }}/{{ .Values.sidecarCertsGenerator.imageRepository }}:{{ .Values.sidecarCertsGenerator.imageTag }}"
  pullPolicy: IfNotPresent

serviceAccount:
  annotations: {}

licenseServer:
  address:
  port: 27000
  
licenseInfo:
  instanceQuantum: 0
  bandwidthPlatinumQuantum: 0
  bandwidthEnterpriseQuantum: 0
  bandwidthStandardQuantum: 0
  vcpuPlatinumQuantum: 0
  vcpuEnterpriseQuantum: 0
  vcpuStandardQuantum: 0
  instanceLowWatermark: 0
  bandwidthPlatinumLowWatermark: 0
  bandwidthEnterpriseLowWatermark: 0
  bandwidthStandardLowWatermark: 0
  vcpuPlatinumLowWatermark: 0
  vcpuStandardLowWatermark: 0
  vcpuEnterpriseLowWatermark: 0
  dbExpireTime: 172800

adcInfo:
  selectorLabel:
    key: adc
    value: citrix

podAnnotations: {}
podSecurityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
imagePullSecrets: []
