# Default values for adm-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageRegistry: quay.io
imageRepository: citrix/adm-agent
imageTag: 14.1-23.31
image: "{{ .Values.imageRegistry }}/{{ .Values.imageRepository }}:{{ .Values.imageTag }}"
pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

accessSecret: ""
admURL: "adm.cloud.com"
loginSecret: ""
clusterPrefix: ""

helper:
  required: false
  imageRegistry: quay.io
  imageRepository: citrix/adm-agent-helper
  imageTag: 2.0.1
  image: "{{ .Values.helper.imageRegistry }}/{{ .Values.helper.imageRepository }}:{{ .Values.helper.imageTag }}"
  pullPolicy: IfNotPresent

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
