#>>>adm-agent-hpa.yaml
{{- if .Values.hpa.required }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "adm-agent.fullname" . }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "adm-agent.fullname" . }}-core
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageValue: {{ .Values.hpa.targetMemoryUtilization }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageValue: {{ .Values.hpa.targetCPUUtilization }}
{{- end }}
#<<<adm-agent-hpa.yaml
