# Default values for citrix-cpx-with-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Citrix ADC CPX config details
image: quay.io/citrix/citrix-k8s-cpx-ingress:13.0-79.64
pullPolicy: IfNotPresent
imagePullSecrets: []

mgmtHttpPort: 9080
mgmtHttpsPort: 9443
openshift: false
nsHTTP2ServerSide: "OFF"
nsCookieVersion: "0"

routeLabels:
namespaceLabels:

# Service Type LoadBalancer and ingress support  with CPX through BGP advertisement
# If you enable this, CPX is run as DaemonSet. Please edit the bgpSettings for configuring
# BGP neighbors for propgation of external IPs.
cpxBgpRouter: false

# If cpxBgpRouter is true, then this is the NSIP used by CPX for internal communication
nsIP: 192.168.1.2

# If cpxBgpRouter is true, then this is the Gateway used by CPX for internal communication
nsGateway: 192.168.1.1

# Protocol used for communication between Citrix Ingress Controller sidecar and Citrix CPX
nsProtocol: http

# External IP for ingress resource when bgpRouter is set to True
ingressIP:

# If IPAM controller is used for auto allocation of the external IP for service of type LoadBalancer, set this option to true
ipam: False

sslCertManagedByAWS: False

nodeSelector:
  key:
  value:
tolerations: []

serviceType:
  loadBalancer:
    enabled: False
    externalTrafficPolicy: "Local"
  nodePort:
    enabled: False
    httpPort:
    httpsPort:

serviceAnnotations: {}

serviceSpec:
  loadBalancerSourceRanges: []

servicePorts: []

# Citrix Ingress Controller config details
cic:
  image: quay.io/citrix/citrix-k8s-ingress-controller:1.18.5
  pullPolicy: IfNotPresent
  required: true
entityPrefix:
license:
  accept: no
ingressClass:
setAsDefaultIngressClass: False
logLevel: INFO
defaultSSLCertSecret:
updateIngressStatus: False
logProxy:
kubernetesURL:

# Citrix ADM/License Server config details
ADMSettings:
  licenseServerIP:
  licenseServerPort: 27000
  ADMIP:
  loginSecret:
  bandWidthLicense: false
  bandWidth:
  vCPULicense: false
  cpxCores:

# Exporter config details
exporter:
  required: false
  image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.8
  pullPolicy: IfNotPresent
  ports:
    containerPort: 8888


# For CRDs supported by Citrix Ingress Controller
crds:
  install: false
  retainOnDelete: false

# Config required to be done by Citrix Ingress Controller for sending metrics to Citrix Observability Exporter
coeConfig:
  required: false
  distributedTracing:
    enable: false
    samplingrate: 100
  endpoint:
    server:
  timeseries:
    port: 5563
    metrics:
      enable: false
      mode: 'avro'
    auditlogs:
      enable: false
    events:
      enable: false
  transactions:
    enable: false
    port: 5557

# BGP configurations: local AS, remote AS and remote address is mandatory to provide. Please do the approrpiate changes with respect to your environment
bgpSettings:
  # When bgpConfig is configured correctly, set the required to true for the configuration to be applied.
  required: false
  bgpConfig:
  - bgpRouter:
      # Local AS number for BGP advertisement
      localAS: 100
      neighbor:
        # Address of the nighbor router for BGP advertisement
      - address:
        # Remote AS number
        remoteAS: 100
        advertisementInterval: 10
        ASOriginationInterval: 10

# Specifies whether a ServiceAccount should be created
serviceAccount:
  create: true
  # The name of the ServiceAccount to use.
  # If not set and `create` is true, a name is generated using the fullname template
  # name:
