# Default values for citrix-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Citrix Ingress Controller config details
image: quay.io/citrix/citrix-k8s-ingress-controller:1.20.5
pullPolicy: IfNotPresent
imagePullSecrets: []
openshift: false
adcCredentialSecret:
nsIP: x.x.x.x
nsVIP:
nsSNIPS:
license:
   accept: no
nsPort: 443
nsProtocol: HTTPS
logLevel: INFO
entityPrefix:
kubernetesURL:
clusterName:
ingressClass:
setAsDefaultIngressClass: False
serviceClass:
defaultSSLCertSecret:
podIPsforServiceGroupMembers: False
ignoreNodeExternalIP: False
ipam: False
# API server Cert verification can be disabled, while communicating with API Server, if disableAPIServerCertVerify set to True
disableAPIServerCertVerify: False
logProxy:
nodeWatch: false
cncPbr: False
nodeSelector:
  key:
  value:
tolerations: []
updateIngressStatus: False
nsHTTP2ServerSide: "OFF"
nsCookieVersion: "0"
resources: {}
## We usually recommend not to specify default resources and to leave this as a conscious
## choice for the user. This also increases chances charts run on environments with little
## resources, such as Minikube. If you do want to specify resources, uncomment the following
## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#   limits:
#     cpu: 100m
#     memory: 100Mi
#   requests:
#     memory: 25Mi

routeLabels:
namespaceLabels:

# Exporter config details
exporter:
  required: false
  image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.9
  pullPolicy: IfNotPresent
  ports:
    containerPort: 8888
  resources: {}
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  ## resources, such as Minikube. If you do want to specify resources, uncomment the following
  ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #   limits:
  #     cpu: 100m
  #     memory: 100Mi
  #   requests:
  #     memory: 25Mi
  #     cpu: 25m


# For CRDs supported by Citrix Ingress Controller
crds:
  install: false
  retainOnDelete: false

# Config required to be done by Citrix Ingress Controller for sending metrics to Citrix Observability Exporter
coeConfig:
  required: false
  distributedTracing:
    enable: false
    samplingrate: 100
  endpoint:
    server:
  timeseries:
    port: 30002
    metrics:
      enable: false
      mode: 'avro'
    auditlogs:
      enable: false
    events:
      enable: false
  transactions:
    enable: false
    port: 30001

# Specifies whether a ServiceAccount should be created
serviceAccount:
  create: true
  # The name of the ServiceAccount to use.
  # If not set and `create` is true, a name is generated using the fullname template
  # name:
