# Default values for NetScaler Observability Exporter
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageRegistry: quay.io
imageRepository: citrix/citrix-observability-exporter
imageTag: 1.10.001
image: "{{ .Values.imageRegistry }}/{{ .Values.imageRepository }}:{{ .Values.imageTag }}"
pullPolicy: IfNotPresent
fullnameOverride: ""
nameOverride: ""
replicas: 1
# license is used accept the terms of the NetScaler license
license:
  accept: no
nodePortRequired: false
headless: false
transaction:
  nodePort:
ns_tracing:
  enabled: false
  server: "zipkin:9411/api/v1/spans" 
splunk:
  enabled: false
  server: ""
  authtoken: ""
  indexprefix: ""
elasticsearch:
  enabled: false
  server: ""
  indexprefix: ""
kafka:
  enabled: false
  broker: ""
  topic: "HTTP"
  dataFormat: "AVRO"
  events: "no"
  auditlogs: "no"
timeseries:
  enabled: false
  nodePort:
json_trans_rate_limiting:
  enabled: false
  limit: 100
  queuelimit: 1000
  window: 5
nsoeLogLevel: "INFO"

podAnnotations: {}
resources: {}
tolerations: []
affinity: {}
