apiVersion: v1
appVersion: "1.18.5"
description: A Helm chart for Citrix Multi-Cluster Ingress Controller configuring MPX/VPX.
name: citrix-multi-cluster-ingress-controller
version: 1.18.5
icon: https://raw.githubusercontent.com/citrix/citrix-helm-charts/gh-pages/icon.png
home: https://www.citrix.com
maintainers:
- name: priyankash-citrix
  email: priyanka.sharma@citrix.com
- name: subashd
  email: subash.dangol@citrix.com
- name: apoorva-05
  email: apoorva.kamath@citrix.com
